name: Trigger auto deployment for container-app-tr7y7ww47x7ha

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-tr7y7ww47x7ha-AutoDeployTrigger-3f61aaa8-1790-4df8-bd77-94e30e2755f7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPTR7Y7WW47X7HA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPTR7Y7WW47X7HA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPTR7Y7WW47X7HA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPTR7Y7WW47X7HA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPTR7Y7WW47X7HA_REGISTRY_PASSWORD }}
          containerAppName: container-app-tr7y7ww47x7ha
          resourceGroup: fastapiej9daa
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


